apiVersion: apps/v1
kind: Deployment
metadata:
  name: news
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news
  template:
    metadata:
      labels:
        app: news
    spec:
      containers:
      - name: news
        image: sanchaym/news:latest
        ports:
        - containerPort: 80
